name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      artifact_debug:
        required: true
        type: boolean
        description: "Artifact Debug"
      artifact_release:
        required: true
        type: boolean
        description: "Artifact Release"

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Execute unit tests
      run: dotnet test

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet publish --runtime win-x64 --configuration ${{ matrix.configuration }} --self-contained false

    - uses: actions/upload-artifact@v3
      if: ${{ (github.event.inputs.artifact_release == 'true' && matrix.configuration == 'Release') || (github.event.inputs.artifact_debug == 'true' && matrix.configuration == 'Debug') }}
      with:
        name: WebFrame-${{ matrix.configuration }}
        path: bin\${{ matrix.configuration }}\net6.0-windows\win-x64\publish
